### ISSUE TITLE
Technical Documentation of Binary Search

### ISSUE THREAD

**Issue by Sayanjones** [sudo-parnab/Its-algober#17]
### 🔖 Feature Description

The current implementation of the binary search function accepts user input without strict type validation. While there's basic error handling for invalid inputs (using try-except), additional improvements can be made, such as type checking for the array and target elements, as well as enforcing that the array is sorted before performing the binary search.

### The feature I'm proposing is to:
- Add type checking to ensure that the input array and target are both integers.
- Sort validation to confirm that the input array is sorted before performing the binary search.
- Handle cases where the array has mixed types or is not sorted.

### 📈 Benefits

Improves user experience by preventing invalid input errors, especially when dealing with unsorted arrays or arrays containing non-integer values. Ensures robustness of the binary search algorithm by checking input validity before executing the core logic.
Prevents unintended behavior that may arise from processing unsorted or improperly formatted data, which can save debugging time for end users.

### 🛠️ Suggested Implementation (Optional)

1. Add a check to ensure that all elements in the input array are integers using a loop or all(isinstance(item, int) for item in arr).
2. Verify if the array is sorted before calling the binary search, and raise an error or sort the array if necessary.
3. Update the except block to handle additional cases, such as mixed data types or unsorted arrays, and provide clear error messages.

### ✔️ Checklist

- [X] I have checked the existing issues to avoid duplicates.
- [X] I have read and understood the [Contributing Guidelines](https://github.com/sudo-parnab/Its-algober/blob/main/CONTRIBUTING.md).
- [X] I have read and agree to the [Code of Conduct](https://github.com/sudo-parnab/Its-algober/blob/main/CODE_OF_CONDUCT.md).
- [X] I am a Hacktoberfest'24 contributor.
- [X] I am willing to work on this issue.

### 📝 Additional Notes (Optional)

This feature will enhance the reliability and user-friendliness of the binary search algorithm, particularly in handling edge cases involving unsorted arrays and mixed-type arrays.

**Comment by phoenix0706** [comment]
@Sayanjones can you assign this issue to me please? I'll be happy to contribute

**Comment by phoenix0706** [comment]
Can you assign this issue to me please?

**Comment by sudo-parnab** [comment]
> Can you assign this issue to me please?

this is a self open issue, open your own issue pls
