### ISSUE TITLE
😍 Add Data Structures Code in C

### ISSUE THREAD

**Issue by sudo-parnab** [sudo-parnab/Its-algober#26]
#### Description:
Help us grow our collection of data structures by contributing code written in **C**. Whether it's basic or advanced structures like Arrays, Linked Lists, Stacks, or Trees, we'd love to see your work.

#### Requirements:
- Ensure the code is modular, with functions split logically.
- Add inline comments to explain key parts of the code.
- Include sample input/output to show the data structure in action.

This is a great opportunity to practice and share your knowledge of C programming!

**Comment by farhan-sayeed** [comment]
@sudo-parnab assign this to me

**Comment by sudo-parnab** [comment]
open a new issue according to your code
