### ISSUE TITLE
 Feature Request: Implement Bubble Sort Algorithm using C

### ISSUE THREAD

**Issue by mdfarmansayeed** [sudo-parnab/Its-algober#27]
### 🔖 Feature Description

**Bubble Sort Algorithm**

Bubble Sort is the simplest sorting algorithm that works by repeatedly swapping the adjacent elements if they are in the wrong order. And here I'll be implementing program for the same in C programming language

### 📈 Benefits

- Bubble sort is easy to understand and implement.
- It does not require any additional memory space.

### 🛠️ Suggested Implementation (Optional)

Bubble sort method is easy to understand & does not require any additional memory space

### ✔️ Checklist

- [X] I have checked the existing issues to avoid duplicates.
- [X] I have read and understood the [Contributing Guidelines](https://github.com/sudo-parnab/Its-algober/blob/main/CONTRIBUTING.md).
- [X] I have read and agree to the [Code of Conduct](https://github.com/sudo-parnab/Its-algober/blob/main/CODE_OF_CONDUCT.md).
- [X] I am a Hacktoberfest'24 contributor.
- [X] I am willing to work on this issue.

### 📝 Additional Notes (Optional)

pls add `hactoberfest` related labels & assign this issue to me

**Comment by sudo-parnab** [comment]
done

**Comment by mdfarmansayeed** [comment]
@sudo-parnab pls merge this with `hacktoberfest` related labels
