### ISSUE TITLE
 Feature Request: Implement Selection Sort Algorithm using C

### ISSUE THREAD

**Issue by mdfarmansayeed** [sudo-parnab/Its-algober#28]
### 🔖 Feature Description

**Selection Sort**
Selection Sort is a comparison-based sorting algorithm. It sorts an array by repeatedly selecting the smallest (or largest) element from the unsorted portion and swapping it with the first unsorted element. This process continues until the entire array is sorted.

### 📈 Benefits

- Requires only a constant O(1) extra memory space.
- It requires less number of swaps (or memory writes) compared to many other standard algorithms. Only cycle sort beats it in terms of memory writes. Therefore it can be simple algorithm choice when memory writes are costly.

### ✔️ Checklist

- [X] I have checked the existing issues to avoid duplicates.
- [X] I have read and understood the [Contributing Guidelines](https://github.com/sudo-parnab/Its-algober/blob/main/CONTRIBUTING.md).
- [X] I have read and agree to the [Code of Conduct](https://github.com/sudo-parnab/Its-algober/blob/main/CODE_OF_CONDUCT.md).
- [X] I am a Hacktoberfest'24 contributor.
- [X] I am willing to work on this issue.

### 📝 Additional Notes (Optional)

pls assign this issue to me

**Comment by mdfarmansayeed** [comment]
@sudo-parnab pls merge this with `hacktoberfest` related labels

**Comment by sudo-parnab** [comment]
> @sudo-parnab pls merge this with `hacktoberfest` related labels

already done
