### ISSUE TITLE
🛠️ Project Proposal: Adding various different algorithms.

### ISSUE THREAD

**Issue by RK-0009** [sudo-parnab/Its-algober#6]
### 🔖 Project Description

This project aims to include different types of algorithms for searching and sorting. It can include various algorithms in different languages.

### 🎤 Project Pitch

This project should be added because it allows beginners the opportunity to work on open-source and contribute.

### 📈 Expected Outcome

The expected outcome is more collaboration in this project.

### ✔️ Checklist

- [X] I have checked and confirmed no similar projects exist.
- [X] I have read and understood the [Contributing Guidelines](https://github.com/sudo-parnab/Its-algober/blob/main/CONTRIBUTING.md).
- [X] I have read and agree to the [Code of Conduct](https://github.com/sudo-parnab/Its-algober/blob/main/CODE_OF_CONDUCT.md).
- [X] I am a Hacktoberfest 2024 contributor.
- [X] I am willing to work on this issue.

**Comment by sudo-parnab** [comment]
Go ahead
